apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/component: back
    app.kubernetes.io/name: test
    app.kubernetes.io/part-of: test
  name: test
  namespace: jenkins
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app.kubernetes.io/component: back
      app.kubernetes.io/name: test
      app.kubernetes.io/part-of: test
  template:
    metadata:
      labels:
        app.kubernetes.io/component: back
        app.kubernetes.io/name: test
        app.kubernetes.io/part-of: test
    spec:
      containers:
        - image: 942083365966.dkr.ecr.us-east-1.amazonaws.com/cicd_test:latest
          name: app
          ports:
            - containerPort: 3000
          resources: {}
      imagePullSecrets:
        - name: aws
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: back
    app.kubernetes.io/name: test
    app.kubernetes.io/part-of: test
  name: test
  namespace: jenkins
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/component: back
    app.kubernetes.io/name: test
    app.kubernetes.io/part-of: test
