apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/component: back
    app.kubernetes.io/name: test
    app.kubernetes.io/part-of: test
  name: test
  namespace: jenkins
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app.kubernetes.io/component: back
    app.kubernetes.io/name: test
    app.kubernetes.io/part-of: test
